### ISSUE TITLE
Client exception in multiplayer with MobEnchantedMessage

### ISSUE THREAD

**Issue by someaddons** [shurf012/EnchantWithMob#1]
In multiplayer the message is throwing exceptions.

```
[18:42:42] [Render thread/WARN]: Res loc exception!:Non [a-z0-9/._-] character in path of location: minecraft:com.baguchan.enchantwithmob.mobenchant.ProtectionMobEnchant@4e791f9d

java.lang.Exception: null
	at net.minecraft.util.ResourceLocationException.handler$zkk000$onException(SourceFile:516) [?:?]
	at net.minecraft.util.ResourceLocationException.<init>(SourceFile:6) [?:?]
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) [?:?]
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38) [?:?]
	at net.minecraft.util.ResourceLocation.func_208304_a(ResourceLocation.java:52) [?:?]
	at com.baguchan.enchantwithmob.utils.MobEnchantUtils.getEnchantFromString(MobEnchantUtils.java:64) [?:1.16.5-1.3.4]
	at com.baguchan.enchantwithmob.message.MobEnchantedMessage.deserialize(MobEnchantedMessage.java:47) [?:1.16.5-1.3.4]
```
You likely want to use the registryname instead of the object toString here:
https://github.com/shurf012/EnchantWithMob/blob/428991e8a6679db63ab947e91779f32139b9562a/src/main/java/com/baguchan/enchantwithmob/message/MobEnchantedMessage.java#L41

**Comment by shurf012** [comment]
fixed in 1.16.5-1.3.5
